add local environment example

diff --git a/examples/service/docker-compose-local.yml b/examples/service/docker-compose-local.yml
--- a/examples/service/docker-compose-local.yml
+++ b/examples/service/docker-compose-local.yml
@@ -1,33 +1,25 @@
 services:
-  gogenexample_integration:
-    container_name: gogenexample_integration
-    build:
-      context: .
-      dockerfile: test.integration.Dockerfile
-    environment:
-      DEPLOY_ENV: "int"
-    depends_on:
-      - gogenexample
-    volumes:
-      - ./target/binutil/dockerize:/usr/bin/dockerize
-      - ./target/report/:/workspace/target/report/
-
   gogenexample:
     image: gogenexampleowner/gogenexample
     container_name: gogenexample
+    environment:
+      DEPLOY_ENV: "local"
     restart: always
     depends_on:
       - gogenexample_smocker_ipify
       - gogenexample_mysql
       - gogenexample_flyway_mysql
     env_file:
-      - target/gogenexample.integration.env
+      - target/gogenexample.cfg.env
     entrypoint: [
         "/usr/bin/dockerize",
         "-wait", "tcp://gogenexample_mysql:3306",
-        "-wait", "tcp://gogenexample_smocker_ipify:8081",
         "/usr/bin/gogenexample"
     ]
+    ports:
+      - "8071:8071"
+      - "8072:8072"
+      - "8073:8073"
     volumes:
       - ./target/binutil/dockerize:/usr/bin/dockerize
 
@@ -64,16 +56,18 @@ services:
       - |
         set -e && \
         echo 'flyway start' && \
-        flyway migrate -url="jdbc:mysql://gogenexample_mysql:3306/gogenexample?allowPublicKeyRetrieval=true&useSSL=false" -user=root -password=root -locations=filesystem:/flyway/sql && \
+        if flyway migrate -url="jdbc:mysql://gogenexample_mysql:3306/gogenexample?allowPublicKeyRetrieval=true&useSSL=false" -user=root -password=root -locations=filesystem:/flyway/sql 2>&1 | tee /dev/stderr | grep -q "ERROR: "; then
+          echo "flyway error!"
+          exit 1
+        fi
         echo 'flyway completed'
-
 
 #  gogenexample_postgres:
 #    container_name: gogenexample_postgres
 #    image: postgres:18
 #    environment:
-#      POSTGRES_USER: root
-#      POSTGRES_PASSWORD: root
+#      POSTGRES_USER: postgres
+#      POSTGRES_PASSWORD: postgres
 #      POSTGRES_DB: gogenexample
 #    ports:
 #      - "9432:5432"
@@ -91,15 +85,15 @@ services:
 #        condition: service_healthy
 #    image: gogenexampleowner/gogenexample_db:latest
 #    container_name: gogenexample_db
+#    restart: "no"
 #    entrypoint: [
-#      "/bin/sh",
-#      "-c",
-#      "set -e && \
-#      echo 'flyway start' && \
-#      flyway migrate \
-#      -url=jdbc:postgresql://gogenexample_postgres:5432/gogenexample \
-#      -user=root \
-#      -password=root \
-#      -locations=filesystem:/flyway/sql && \
-#      echo 'flyway completed'"
-#    ]
+#      - /bin/sh
+#      - -c
+#      - |
+#        set -e
+#        echo 'flyway start'
+#        if flyway migrate -url=jdbc:postgresql://gogenexample_postgres:5432/gogenexample -user=postgres -password=postgres -locations=filesystem:/flyway/sql 2>&1 | tee /dev/stderr | grep -q "ERROR: "; then
+#          echo "flyway error!"
+#          exit 1
+#        fi
+#        echo 'flyway completed'
